/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as EventBusRouteImport } from './routes/event-bus'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CronRouteImport } from './routes/cron'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsNameRouteImport } from './routes/teams.$name'
import { Route as SessionsIdRouteImport } from './routes/sessions.$id'
import { Route as ChatTeamRouteImport } from './routes/chat.team'
import { Route as ChatAgentNameRouteImport } from './routes/chat.$agentName'
import { Route as ChatTeamTeamNameRouteImport } from './routes/chat.team.$teamName'
import { Route as ChatAgentNameSessionIdRouteImport } from './routes/chat.$agentName.$sessionId'
import { Route as ChatTeamTeamNameAgentNameRouteImport } from './routes/chat.team.$teamName.$agentName'
import { Route as ChatTeamTeamNameAgentNameSessionIdRouteImport } from './routes/chat.team.$teamName.$agentName.$sessionId'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const EventBusRoute = EventBusRouteImport.update({
  id: '/event-bus',
  path: '/event-bus',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRoute = CronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsNameRoute = TeamsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => TeamsRoute,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SessionsRoute,
} as any)
const ChatTeamRoute = ChatTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAgentNameRoute = ChatAgentNameRouteImport.update({
  id: '/$agentName',
  path: '/$agentName',
  getParentRoute: () => ChatRoute,
} as any)
const ChatTeamTeamNameRoute = ChatTeamTeamNameRouteImport.update({
  id: '/$teamName',
  path: '/$teamName',
  getParentRoute: () => ChatTeamRoute,
} as any)
const ChatAgentNameSessionIdRoute = ChatAgentNameSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ChatAgentNameRoute,
} as any)
const ChatTeamTeamNameAgentNameRoute =
  ChatTeamTeamNameAgentNameRouteImport.update({
    id: '/$agentName',
    path: '/$agentName',
    getParentRoute: () => ChatTeamTeamNameRoute,
  } as any)
const ChatTeamTeamNameAgentNameSessionIdRoute =
  ChatTeamTeamNameAgentNameSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => ChatTeamTeamNameAgentNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/cron': typeof CronRoute
  '/dashboard': typeof DashboardRoute
  '/event-bus': typeof EventBusRoute
  '/extensions': typeof ExtensionsRoute
  '/logs': typeof LogsRoute
  '/registry': typeof RegistryRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/teams': typeof TeamsRouteWithChildren
  '/chat/$agentName': typeof ChatAgentNameRouteWithChildren
  '/chat/team': typeof ChatTeamRouteWithChildren
  '/sessions/$id': typeof SessionsIdRoute
  '/teams/$name': typeof TeamsNameRoute
  '/chat/$agentName/$sessionId': typeof ChatAgentNameSessionIdRoute
  '/chat/team/$teamName': typeof ChatTeamTeamNameRouteWithChildren
  '/chat/team/$teamName/$agentName': typeof ChatTeamTeamNameAgentNameRouteWithChildren
  '/chat/team/$teamName/$agentName/$sessionId': typeof ChatTeamTeamNameAgentNameSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/cron': typeof CronRoute
  '/dashboard': typeof DashboardRoute
  '/event-bus': typeof EventBusRoute
  '/extensions': typeof ExtensionsRoute
  '/logs': typeof LogsRoute
  '/registry': typeof RegistryRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/teams': typeof TeamsRouteWithChildren
  '/chat/$agentName': typeof ChatAgentNameRouteWithChildren
  '/chat/team': typeof ChatTeamRouteWithChildren
  '/sessions/$id': typeof SessionsIdRoute
  '/teams/$name': typeof TeamsNameRoute
  '/chat/$agentName/$sessionId': typeof ChatAgentNameSessionIdRoute
  '/chat/team/$teamName': typeof ChatTeamTeamNameRouteWithChildren
  '/chat/team/$teamName/$agentName': typeof ChatTeamTeamNameAgentNameRouteWithChildren
  '/chat/team/$teamName/$agentName/$sessionId': typeof ChatTeamTeamNameAgentNameSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/cron': typeof CronRoute
  '/dashboard': typeof DashboardRoute
  '/event-bus': typeof EventBusRoute
  '/extensions': typeof ExtensionsRoute
  '/logs': typeof LogsRoute
  '/registry': typeof RegistryRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/teams': typeof TeamsRouteWithChildren
  '/chat/$agentName': typeof ChatAgentNameRouteWithChildren
  '/chat/team': typeof ChatTeamRouteWithChildren
  '/sessions/$id': typeof SessionsIdRoute
  '/teams/$name': typeof TeamsNameRoute
  '/chat/$agentName/$sessionId': typeof ChatAgentNameSessionIdRoute
  '/chat/team/$teamName': typeof ChatTeamTeamNameRouteWithChildren
  '/chat/team/$teamName/$agentName': typeof ChatTeamTeamNameAgentNameRouteWithChildren
  '/chat/team/$teamName/$agentName/$sessionId': typeof ChatTeamTeamNameAgentNameSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/cron'
    | '/dashboard'
    | '/event-bus'
    | '/extensions'
    | '/logs'
    | '/registry'
    | '/sessions'
    | '/settings'
    | '/shared'
    | '/teams'
    | '/chat/$agentName'
    | '/chat/team'
    | '/sessions/$id'
    | '/teams/$name'
    | '/chat/$agentName/$sessionId'
    | '/chat/team/$teamName'
    | '/chat/team/$teamName/$agentName'
    | '/chat/team/$teamName/$agentName/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/cron'
    | '/dashboard'
    | '/event-bus'
    | '/extensions'
    | '/logs'
    | '/registry'
    | '/sessions'
    | '/settings'
    | '/shared'
    | '/teams'
    | '/chat/$agentName'
    | '/chat/team'
    | '/sessions/$id'
    | '/teams/$name'
    | '/chat/$agentName/$sessionId'
    | '/chat/team/$teamName'
    | '/chat/team/$teamName/$agentName'
    | '/chat/team/$teamName/$agentName/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/cron'
    | '/dashboard'
    | '/event-bus'
    | '/extensions'
    | '/logs'
    | '/registry'
    | '/sessions'
    | '/settings'
    | '/shared'
    | '/teams'
    | '/chat/$agentName'
    | '/chat/team'
    | '/sessions/$id'
    | '/teams/$name'
    | '/chat/$agentName/$sessionId'
    | '/chat/team/$teamName'
    | '/chat/team/$teamName/$agentName'
    | '/chat/team/$teamName/$agentName/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  CronRoute: typeof CronRoute
  DashboardRoute: typeof DashboardRoute
  EventBusRoute: typeof EventBusRoute
  ExtensionsRoute: typeof ExtensionsRoute
  LogsRoute: typeof LogsRoute
  RegistryRoute: typeof RegistryRoute
  SessionsRoute: typeof SessionsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SharedRoute: typeof SharedRoute
  TeamsRoute: typeof TeamsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-bus': {
      id: '/event-bus'
      path: '/event-bus'
      fullPath: '/event-bus'
      preLoaderRoute: typeof EventBusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron': {
      id: '/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof CronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$name': {
      id: '/teams/$name'
      path: '/$name'
      fullPath: '/teams/$name'
      preLoaderRoute: typeof TeamsNameRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/chat/team': {
      id: '/chat/team'
      path: '/team'
      fullPath: '/chat/team'
      preLoaderRoute: typeof ChatTeamRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/$agentName': {
      id: '/chat/$agentName'
      path: '/$agentName'
      fullPath: '/chat/$agentName'
      preLoaderRoute: typeof ChatAgentNameRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/team/$teamName': {
      id: '/chat/team/$teamName'
      path: '/$teamName'
      fullPath: '/chat/team/$teamName'
      preLoaderRoute: typeof ChatTeamTeamNameRouteImport
      parentRoute: typeof ChatTeamRoute
    }
    '/chat/$agentName/$sessionId': {
      id: '/chat/$agentName/$sessionId'
      path: '/$sessionId'
      fullPath: '/chat/$agentName/$sessionId'
      preLoaderRoute: typeof ChatAgentNameSessionIdRouteImport
      parentRoute: typeof ChatAgentNameRoute
    }
    '/chat/team/$teamName/$agentName': {
      id: '/chat/team/$teamName/$agentName'
      path: '/$agentName'
      fullPath: '/chat/team/$teamName/$agentName'
      preLoaderRoute: typeof ChatTeamTeamNameAgentNameRouteImport
      parentRoute: typeof ChatTeamTeamNameRoute
    }
    '/chat/team/$teamName/$agentName/$sessionId': {
      id: '/chat/team/$teamName/$agentName/$sessionId'
      path: '/$sessionId'
      fullPath: '/chat/team/$teamName/$agentName/$sessionId'
      preLoaderRoute: typeof ChatTeamTeamNameAgentNameSessionIdRouteImport
      parentRoute: typeof ChatTeamTeamNameAgentNameRoute
    }
  }
}

interface ChatAgentNameRouteChildren {
  ChatAgentNameSessionIdRoute: typeof ChatAgentNameSessionIdRoute
}

const ChatAgentNameRouteChildren: ChatAgentNameRouteChildren = {
  ChatAgentNameSessionIdRoute: ChatAgentNameSessionIdRoute,
}

const ChatAgentNameRouteWithChildren = ChatAgentNameRoute._addFileChildren(
  ChatAgentNameRouteChildren,
)

interface ChatTeamTeamNameAgentNameRouteChildren {
  ChatTeamTeamNameAgentNameSessionIdRoute: typeof ChatTeamTeamNameAgentNameSessionIdRoute
}

const ChatTeamTeamNameAgentNameRouteChildren: ChatTeamTeamNameAgentNameRouteChildren =
  {
    ChatTeamTeamNameAgentNameSessionIdRoute:
      ChatTeamTeamNameAgentNameSessionIdRoute,
  }

const ChatTeamTeamNameAgentNameRouteWithChildren =
  ChatTeamTeamNameAgentNameRoute._addFileChildren(
    ChatTeamTeamNameAgentNameRouteChildren,
  )

interface ChatTeamTeamNameRouteChildren {
  ChatTeamTeamNameAgentNameRoute: typeof ChatTeamTeamNameAgentNameRouteWithChildren
}

const ChatTeamTeamNameRouteChildren: ChatTeamTeamNameRouteChildren = {
  ChatTeamTeamNameAgentNameRoute: ChatTeamTeamNameAgentNameRouteWithChildren,
}

const ChatTeamTeamNameRouteWithChildren =
  ChatTeamTeamNameRoute._addFileChildren(ChatTeamTeamNameRouteChildren)

interface ChatTeamRouteChildren {
  ChatTeamTeamNameRoute: typeof ChatTeamTeamNameRouteWithChildren
}

const ChatTeamRouteChildren: ChatTeamRouteChildren = {
  ChatTeamTeamNameRoute: ChatTeamTeamNameRouteWithChildren,
}

const ChatTeamRouteWithChildren = ChatTeamRoute._addFileChildren(
  ChatTeamRouteChildren,
)

interface ChatRouteChildren {
  ChatAgentNameRoute: typeof ChatAgentNameRouteWithChildren
  ChatTeamRoute: typeof ChatTeamRouteWithChildren
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatAgentNameRoute: ChatAgentNameRouteWithChildren,
  ChatTeamRoute: ChatTeamRouteWithChildren,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SessionsRouteChildren {
  SessionsIdRoute: typeof SessionsIdRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsIdRoute: SessionsIdRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

interface TeamsRouteChildren {
  TeamsNameRoute: typeof TeamsNameRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsNameRoute: TeamsNameRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  CronRoute: CronRoute,
  DashboardRoute: DashboardRoute,
  EventBusRoute: EventBusRoute,
  ExtensionsRoute: ExtensionsRoute,
  LogsRoute: LogsRoute,
  RegistryRoute: RegistryRoute,
  SessionsRoute: SessionsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SharedRoute: SharedRoute,
  TeamsRoute: TeamsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
