/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CronRouteImport } from './routes/cron'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrincipalPrincipalNameRouteImport } from './routes/principal.$principalName'
import { Route as LogPrincipalNameRouteImport } from './routes/log.$principalName'
import { Route as ChatPrincipalNameRouteImport } from './routes/chat.$principalName'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRoute = CronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalPrincipalNameRoute = PrincipalPrincipalNameRouteImport.update({
  id: '/principal/$principalName',
  path: '/principal/$principalName',
  getParentRoute: () => rootRouteImport,
} as any)
const LogPrincipalNameRoute = LogPrincipalNameRouteImport.update({
  id: '/log/$principalName',
  path: '/log/$principalName',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPrincipalNameRoute = ChatPrincipalNameRouteImport.update({
  id: '/$principalName',
  path: '/$principalName',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/cron': typeof CronRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/extensions': typeof ExtensionsRoute
  '/registry': typeof RegistryRoute
  '/settings': typeof SettingsRoute
  '/chat/$principalName': typeof ChatPrincipalNameRoute
  '/log/$principalName': typeof LogPrincipalNameRoute
  '/principal/$principalName': typeof PrincipalPrincipalNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/cron': typeof CronRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/extensions': typeof ExtensionsRoute
  '/registry': typeof RegistryRoute
  '/settings': typeof SettingsRoute
  '/chat/$principalName': typeof ChatPrincipalNameRoute
  '/log/$principalName': typeof LogPrincipalNameRoute
  '/principal/$principalName': typeof PrincipalPrincipalNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/cron': typeof CronRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/extensions': typeof ExtensionsRoute
  '/registry': typeof RegistryRoute
  '/settings': typeof SettingsRoute
  '/chat/$principalName': typeof ChatPrincipalNameRoute
  '/log/$principalName': typeof LogPrincipalNameRoute
  '/principal/$principalName': typeof PrincipalPrincipalNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/cron'
    | '/dashboard'
    | '/discover'
    | '/extensions'
    | '/registry'
    | '/settings'
    | '/chat/$principalName'
    | '/log/$principalName'
    | '/principal/$principalName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/cron'
    | '/dashboard'
    | '/discover'
    | '/extensions'
    | '/registry'
    | '/settings'
    | '/chat/$principalName'
    | '/log/$principalName'
    | '/principal/$principalName'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/cron'
    | '/dashboard'
    | '/discover'
    | '/extensions'
    | '/registry'
    | '/settings'
    | '/chat/$principalName'
    | '/log/$principalName'
    | '/principal/$principalName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  CronRoute: typeof CronRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  ExtensionsRoute: typeof ExtensionsRoute
  RegistryRoute: typeof RegistryRoute
  SettingsRoute: typeof SettingsRoute
  LogPrincipalNameRoute: typeof LogPrincipalNameRoute
  PrincipalPrincipalNameRoute: typeof PrincipalPrincipalNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron': {
      id: '/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof CronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal/$principalName': {
      id: '/principal/$principalName'
      path: '/principal/$principalName'
      fullPath: '/principal/$principalName'
      preLoaderRoute: typeof PrincipalPrincipalNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log/$principalName': {
      id: '/log/$principalName'
      path: '/log/$principalName'
      fullPath: '/log/$principalName'
      preLoaderRoute: typeof LogPrincipalNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$principalName': {
      id: '/chat/$principalName'
      path: '/$principalName'
      fullPath: '/chat/$principalName'
      preLoaderRoute: typeof ChatPrincipalNameRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatPrincipalNameRoute: typeof ChatPrincipalNameRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatPrincipalNameRoute: ChatPrincipalNameRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  CronRoute: CronRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  ExtensionsRoute: ExtensionsRoute,
  RegistryRoute: RegistryRoute,
  SettingsRoute: SettingsRoute,
  LogPrincipalNameRoute: LogPrincipalNameRoute,
  PrincipalPrincipalNameRoute: PrincipalPrincipalNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
