/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as EventBusRouteImport } from './routes/event-bus'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DaemonLogsRouteImport } from './routes/daemon-logs'
import { Route as CronRouteImport } from './routes/cron'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogPrincipalNameRouteImport } from './routes/log.$principalName'
import { Route as ChatPrincipalNameRouteImport } from './routes/chat.$principalName'

const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const EventBusRoute = EventBusRouteImport.update({
  id: '/event-bus',
  path: '/event-bus',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DaemonLogsRoute = DaemonLogsRouteImport.update({
  id: '/daemon-logs',
  path: '/daemon-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRoute = CronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogPrincipalNameRoute = LogPrincipalNameRouteImport.update({
  id: '/log/$principalName',
  path: '/log/$principalName',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPrincipalNameRoute = ChatPrincipalNameRouteImport.update({
  id: '/$principalName',
  path: '/$principalName',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/cron': typeof CronRoute
  '/daemon-logs': typeof DaemonLogsRoute
  '/dashboard': typeof DashboardRoute
  '/event-bus': typeof EventBusRoute
  '/extensions': typeof ExtensionsRoute
  '/registry': typeof RegistryRoute
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/chat/$principalName': typeof ChatPrincipalNameRoute
  '/log/$principalName': typeof LogPrincipalNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/cron': typeof CronRoute
  '/daemon-logs': typeof DaemonLogsRoute
  '/dashboard': typeof DashboardRoute
  '/event-bus': typeof EventBusRoute
  '/extensions': typeof ExtensionsRoute
  '/registry': typeof RegistryRoute
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/chat/$principalName': typeof ChatPrincipalNameRoute
  '/log/$principalName': typeof LogPrincipalNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/cron': typeof CronRoute
  '/daemon-logs': typeof DaemonLogsRoute
  '/dashboard': typeof DashboardRoute
  '/event-bus': typeof EventBusRoute
  '/extensions': typeof ExtensionsRoute
  '/registry': typeof RegistryRoute
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/chat/$principalName': typeof ChatPrincipalNameRoute
  '/log/$principalName': typeof LogPrincipalNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/cron'
    | '/daemon-logs'
    | '/dashboard'
    | '/event-bus'
    | '/extensions'
    | '/registry'
    | '/settings'
    | '/shared'
    | '/chat/$principalName'
    | '/log/$principalName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/cron'
    | '/daemon-logs'
    | '/dashboard'
    | '/event-bus'
    | '/extensions'
    | '/registry'
    | '/settings'
    | '/shared'
    | '/chat/$principalName'
    | '/log/$principalName'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/cron'
    | '/daemon-logs'
    | '/dashboard'
    | '/event-bus'
    | '/extensions'
    | '/registry'
    | '/settings'
    | '/shared'
    | '/chat/$principalName'
    | '/log/$principalName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  CronRoute: typeof CronRoute
  DaemonLogsRoute: typeof DaemonLogsRoute
  DashboardRoute: typeof DashboardRoute
  EventBusRoute: typeof EventBusRoute
  ExtensionsRoute: typeof ExtensionsRoute
  RegistryRoute: typeof RegistryRoute
  SettingsRoute: typeof SettingsRoute
  SharedRoute: typeof SharedRoute
  LogPrincipalNameRoute: typeof LogPrincipalNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-bus': {
      id: '/event-bus'
      path: '/event-bus'
      fullPath: '/event-bus'
      preLoaderRoute: typeof EventBusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daemon-logs': {
      id: '/daemon-logs'
      path: '/daemon-logs'
      fullPath: '/daemon-logs'
      preLoaderRoute: typeof DaemonLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron': {
      id: '/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof CronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log/$principalName': {
      id: '/log/$principalName'
      path: '/log/$principalName'
      fullPath: '/log/$principalName'
      preLoaderRoute: typeof LogPrincipalNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$principalName': {
      id: '/chat/$principalName'
      path: '/$principalName'
      fullPath: '/chat/$principalName'
      preLoaderRoute: typeof ChatPrincipalNameRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatPrincipalNameRoute: typeof ChatPrincipalNameRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatPrincipalNameRoute: ChatPrincipalNameRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  CronRoute: CronRoute,
  DaemonLogsRoute: DaemonLogsRoute,
  DashboardRoute: DashboardRoute,
  EventBusRoute: EventBusRoute,
  ExtensionsRoute: ExtensionsRoute,
  RegistryRoute: RegistryRoute,
  SettingsRoute: SettingsRoute,
  SharedRoute: SharedRoute,
  LogPrincipalNameRoute: LogPrincipalNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
